# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "NSObject.rb"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["James Paolantonio"]
  s.date = "2012-06-25"
  s.description = "Active Record Rails models to native Objective-C.  It allows you to generate Objective-C Models of your Active Record resources."
  s.email = "jamespaolantonio@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    "README.md",
    "Rakefile",
    "lib/generators/ajax/README.md",
    "lib/generators/ajax/base.rb",
    "lib/generators/ajax/model/Objc.rb",
    "lib/generators/ajax/model/model_generator.rb",
    "lib/generators/ajax/model/templates/NSObject.h.rb.erb",
    "lib/generators/ajax/model/templates/NSObject.m.rb.erb",
    "lib/lotusfeet-rails3-generators.rb"
  ]
  s.homepage = "https://github.com/jPaolantonio/NSObject.rb"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Active Record Rails models to native Objective-C."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

